
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 15 16:59:59 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int CASE = 25;
  public static final int NOTEQUAL = 31;
  public static final int LPAREN = 12;
  public static final int GREATER = 32;
  public static final int SEMI = 7;
  public static final int CONTINUE = 18;
  public static final int MINUS = 39;
  public static final int LESS = 34;
  public static final int FOR = 23;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 13;
  public static final int AND = 36;
  public static final int LESSEQUAL = 35;
  public static final int OR = 37;
  public static final int BOOL = 47;
  public static final int COMMA = 8;
  public static final int INC = 26;
  public static final int DIV = 41;
  public static final int PLUS = 38;
  public static final int ASSIGN = 6;
  public static final int IF = 15;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 30;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int MUL = 40;
  public static final int NUMBER = 46;
  public static final int MOD = 42;
  public static final int IDENT = 45;
  public static final int BREAK = 17;
  public static final int VOID = 14;
  public static final int SWITCH = 22;
  public static final int GREATEREQUAL = 33;
  public static final int COLON = 24;
  public static final int LBRACE = 3;
  public static final int ELSE = 16;
  public static final int ENUM = 11;
  public static final int READ = 20;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 43;
  public static final int DEC = 27;
  public static final int PRINT = 21;
  public static final int LENGTH = 29;
}

